### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ramiroaraujo** [mfedko/idea-file-language#1]
Hey! Just feedback, it get nice exception when trying to start PHPStorm. I cannot copy the text from the modal error window, but it basically says: Unsupported major.minor version 52.0 for this plugin

I'm on OSX 10.10.5 and PHPStorm 9.0.2

Let me know if you need any more info

**Comment by mfedko** [comment]
hi, I don't have OSX for test, what is your Java version?
You can see it in help -> about -> JRE

I've just updated the plugin and used JDK8, if that not works I can downgrade it to Java 6 back

**Comment by denisvmedia** [comment]
I've just updated to the latest version and I'm getting this problem in PHPStorm 9.0.2 (this is probably the same issue).

```
com.github.mfedko.idea.plugins.filelanguage.FileLanguageProjectComponent@65207178: INSTANCE
java.lang.NoSuchFieldError: INSTANCE
    at com.github.mfedko.idea.plugins.filelanguage.FileLanguagePanel.<init>(FileLanguagePanel.java:70)
    at com.github.mfedko.idea.plugins.filelanguage.FileLanguageProjectComponent.projectOpened(FileLanguageProjectComponent.java:23)
    at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:393)
    at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:73)
    at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:428)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$3.projectOpened(ProjectManagerImpl.java:154)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:938)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:461)
    at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:222)
    at com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirectoryProjectsManager.java:56)
    at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:357)
    at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:384)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
    at com.sun.proxy.$Proxy42.appStarting(Unknown Source)
    at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:328)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by mfedko** [comment]
Please, try a 0.1.0 version

**Comment by denisvmedia** [comment]
Em... I checked for updates, but it doesn't show anything new... Still 0.0.3 is the most recent one.

**Comment by mfedko** [comment]
It's passing a review, for now you cant try to manually install it from disk - https://www.dropbox.com/s/ivcnus4jt90yqgh/idea-file-language-0.1.1.zip?dl=0

**Comment by ramiroaraujo** [comment]
sorry for the feedback delay. It's still happening to me in 0.1.1, but I gave you the wrong Java version. Webstorm says JRE 1.6.0_65-b14-466.1-11M416 x86_64. I had run `java -version` in the terminal and though they should be the same
